/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BBid: typeof import('./components/Bid/B-Bid.vue')['default']
    DecisionForm: typeof import('./components/DecisionForm/DecisionForm.vue')['default']
    DFAllocation: typeof import('./components/DecisionForm/DF-Allocation.vue')['default']
    DFBid: typeof import('./components/DecisionForm/DF-Bid.vue')['default']
    DFEquipment: typeof import('./components/DecisionForm/DF-Equipment.vue')['default']
    DFLoan: typeof import('./components/DecisionForm/DF-Loan.vue')['default']
    DFNextWeek: typeof import('./components/DecisionForm/DF-NextWeek.vue')['default']
    DFWorkers: typeof import('./components/DecisionForm/DF-Workers.vue')['default']
    Event: typeof import('./components/Event/Event.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/TopBar/TopBar.vue')['default']
    WeeklyReport: typeof import('./components/WeeklyReport/WeeklyReport.vue')['default']
    WRAllocation: typeof import('./components/WeeklyReport/WR-Allocation.vue')['default']
    WRFinances: typeof import('./components/WeeklyReport/WR-Finances.vue')['default']
    WRWorkers: typeof import('./components/WeeklyReport/WR-Workers.vue')['default']
  }
}
