/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUsersDialog: typeof import('./components/Admin/AddUsersDialog.vue')['default']
    AdminActionMenu: typeof import('./components/Admin/AdminActionMenu.vue')['default']
    AdminNavigation: typeof import('./components/Admin/AdminNavigation.vue')['default']
    AdminNavigationLink: typeof import('./components/Admin/AdminNavigationLink.vue')['default']
    AdminNotStarted: typeof import('./components/Admin/AdminNotStarted.vue')['default']
    AdminTable: typeof import('./components/Admin/AdminTable.vue')['default']
    BidTable: typeof import('./components/Admin/BidTable.vue')['default']
    ConfidenceChart: typeof import('./components/Admin/Charts/ConfidenceChart.vue')['default']
    ConfirmationDialog: typeof import('./components/Admin/ConfirmationDialog.vue')['default']
    DecisionForm: typeof import('./components/DecisionForm/DecisionForm.vue')['default']
    DFAllocation: typeof import('./components/DecisionForm/DF-Allocation.vue')['default']
    DFBid: typeof import('./components/DecisionForm/DF-Bid.vue')['default']
    DFDoneButton: typeof import('./components/DecisionForm/DF-DoneButton.vue')['default']
    DFEquipment: typeof import('./components/DecisionForm/DF-Equipment.vue')['default']
    DFLoan: typeof import('./components/DecisionForm/DF-Loan.vue')['default']
    DFWorkers: typeof import('./components/DecisionForm/DF-Workers.vue')['default']
    DurationDistributionChart: typeof import('./components/Admin/Charts/DurationDistributionChart.vue')['default']
    Event: typeof import('./components/Event/Event.vue')['default']
    GameFinishDialog: typeof import('./components/GameFinishDialog.vue')['default']
    GameFinished: typeof import('./components/GameFinished.vue')['default']
    GameHeader: typeof import('./components/GameHeader.vue')['default']
    GameProgressTable: typeof import('./components/Admin/GameProgressTable.vue')['default']
    PriceDistributionChart: typeof import('./components/Admin/Charts/PriceDistributionChart.vue')['default']
    RestartGame: typeof import('./components/RestartGame.vue')['default']
    ResultsTable: typeof import('./components/Admin/ResultsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section1: typeof import('./components/Survey/Section1.vue')['default']
    Section2: typeof import('./components/Survey/Section2.vue')['default']
    Section3: typeof import('./components/Survey/Section3.vue')['default']
    Survey: typeof import('./components/Survey/Survey.vue')['default']
    SurveyTable: typeof import('./components/Admin/SurveyTable.vue')['default']
    WeeklyReport: typeof import('./components/WeeklyReport/WeeklyReport.vue')['default']
    WRAllocation: typeof import('./components/WeeklyReport/WR-Allocation.vue')['default']
    WRFinances: typeof import('./components/WeeklyReport/WR-Finances.vue')['default']
    WRWorkers: typeof import('./components/WeeklyReport/WR-Workers.vue')['default']
  }
}
